-- CAKES
INSERT INTO CAKES (NAME, PRICE, INGREDIENTS) VALUES
('Torta Margherita', 100, 'Uova, Farina, Latte, Lievito'),
('Tiramisù', 150, 'Uova, mascarpone, caffè, biscotti');

-- ORDERS
INSERT INTO ORDERS (AMOUNT, CREATION_TIMESTAMP, CAKE_ID) VALUES
(1, CURRENT_TIMESTAMP, 1),
(2, CURRENT_TIMESTAMP-1, 1),
(3, CURRENT_TIMESTAMP-2, 1),
(4, CURRENT_TIMESTAMP-3, 1),
(5, CURRENT_TIMESTAMP-4, 1)
